version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_librarydb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    environment:
      LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.xml
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/librarydb
      LIQUIBASE_USERNAME: postgres
      LIQUIBASE_PASSWORD: 12345678
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["bash", "-c", "until pg_isready -h postgres -p 5432; do echo waiting for postgres; sleep 2; done; liquibase update"]
  app:
    build: .
    container_name: library_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/librarydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678

volumes:
  postgres-data:
    driver: local
