spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  # H2 configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: false

  # Logging configuration
logging:
  level:
    org:
#      springframework:
      ##        security: DEBUG
      ##        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE