server:
  port: 8080

# Spring Profiles
spring:
  profiles:
    active: local

  # Spring Security - JWT configuration
  jwt:
    secret: "secret-key-for-jwt"
    expiration: 86400000  # 1 day


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html