spring:
  # PostgreSQL configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase configuration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml